name: Coordinate
version: '${project.version}'
main: shigera9.coordinate.Coordinate
api-version: 1.19

commands:
  cie:
    description: Toggles the Coordinate display on/off
    permission: Coordinate.command.cie
    permission-message: You don't have permission to perform this command.
    #usage

permissions:
  Coordinate.command.cie:
    description: Allows you to perform /cie command.
    default: op


